language: python
python:
  - "2.7"
install:
  - pip install python-coveralls  # Add me to install python-coveralls
script:
  - python setup.py install
after_success:
  - coveralls                     # Add me to upload reports to coveralls.io
